
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build custom index.html
        run: |
          mkdir -p public
          echo "<!DOCTYPE html><html><head><title>My Page</title></head><body><h1>Hello from custom build!</h1></body></html>" > _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    needs: build
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
